version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: myapp
    ports:
      - "4321:4321"
    volumes:
      - ./app:/usr/src/app
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
    external: true
